### ISSUE TITLE
Change the type of records

### ISSUE THREAD

**Issue by gzm0** [scala-records/scala-records#111]
Currently, we use vampire-structural types to represent records. This is an issue notably since it requires hacks like #95 to write the type of a record.

After discussions with @cvogt, we came to the conclusion, that expressing record types as follows is probably better:

```scala
Rec[{ def name: String, def age: Int }]
```

access to the fields of the records will be provided by implicit conversion:

```scala
implicit def accessRecord[T](rec: Rec[T]): T
```

which materializes the structural type with macro members (that forward to the argument, just as they do forward to the receiver now).

This brings the huge advantage, that the vampire-macro members **never travel** in the program. Therefore they cannot get lost. Hence, the type of a record can safely be written without any macros.

First experiments have shown, that autocompletion does work in the Scala IDE. Further, once a record type is written, no whitebox macros are requried. Therefore, the chances of this working in IntelliJ are high.

Lastly, this brings an advantage, once collections of multiple records are created. Consider this use case (inspired by Spark 1.3):

```scala
class DataFrame[Fields] {
  def getRow(i: Int): Rec[Fields]
}
```

A concrete `DataFrame` type would now look like this:

```scala
DataFrame[{ def name: String, def age: Int }]
```

Obvious what it does & simple to map to records, without any macro magic.

**Comment by gzm0** [comment]
@vjovanov @hubertp @heathermiller opinions?

**Comment by cvogt** [comment]
Also I my macros successfully implement this. Some insights from @gzm0 how you guys handle some internals, e.g. generate an anonymous class with macro members, allowed me to further refine it.

**Comment by gzm0** [comment]
As soon as I have green light on this, I will proceed in migrating to this. @cvogt I guess you agree that we should do this change first, before we merge in your stuff.

**Comment by cvogt** [comment]
@gzm0 I agree, we first need to converge on this matter. Only after that merging makes sense.

**Comment by vjovanov** [comment]
Interesting, if we can make it work it would be quite a nice solution for recrods in Scala. I have a bunch of questions:
  - Can we make this work without reflective accesses? How does the `Rep[T] => T` conversion get around reflective checks if we use black box macros only?
  - Does the auto-completion work in the REPL? Can we make it work?

I agree with this path, but only if it matches all the requirements of Scala Records. Luckily we have all the things ready to check this (e.g., performance benchmarks, eclipse benchmarks, etc.). 

I am available for hacking after April 02.

**Comment by cvogt** [comment]
@vjovanov Mine isn't a blackbox macro right now, but a whitebox macro with a good enough signature for code-completion (IntelliJ may think there is reflective access, not sure, but there certainly isn't). It generates an anonymous class with macro members, so no reflective access.

Auto-completion does not work in the Scala REPL, because it does not see implicit conversions. Auto-completion works find in the Ammonite Scala REPL. Since the native Scala REPL is so limited and there is an alternative, I doubt it would be wise to let it constrain our design.

**Comment by vjovanov** [comment]
@gzm0 which REPL does Spark use?

**Comment by vjovanov** [comment]
@cvogt Can you define other implicits over `Rec[...]`? I think macro implicits do not allow existence of any other implicits...

Does auto-completion work with implicit materializers that I used in LMS?

**Comment by gzm0** [comment]
> which REPL does Spark use?

Spark uses a hacked version of the Scala REPL.

**Comment by vjovanov** [comment]
Hm, maybe we could improve the REPL to pick up implicit conversions. I guess we can port the code from Ammonite. Not a blocker I would say.
