### ISSUE TITLE
Release for Scala.js 0.6

### ISSUE THREAD

**Issue by hrj** [scala-records/scala-records#115]

**Comment by gzm0** [comment]
Scala-records are released for Scala.js since version 0.2 (current version is 0.3).

**Comment by hrj** [comment]
I see the problem now. I am using scala-js version 0.6.x while the published version seems to be targeted for scala-js 0.5.x. Hence, sbt couldn't resolve the dependency.

Can you please publish for the latest scala-js version too?

**Comment by gzm0** [comment]
Oh, indeed. Sorry about that. We'll have to publish a new version I assume.

**Comment by vjovanov** [comment]
Fixed in version 0.4.

**Comment by gzm0** [comment]
@vjovanov don't forget to release for 2.10.

**Comment by vjovanov** [comment]
Thx for reminding. I will do this tomorrow and include the release instructions.
