### ISSUE TITLE
Allow symbols for literal record construction

### ISSUE THREAD

**Issue by gzm0** [scala-records/scala-records#96]
This should work:

```scala
Rec('name -> "Hanna")
```

**Comment by cvogt** [comment]
How about this instead: `Rec(name = "Hanna")`? This would give record construction the same syntax like case class copy methods.

**Comment by cvogt** [comment]
There is already `Record(name="Hanna")` and `Record("name" -> "Hanna")`. Any reason to have a third syntax?

**Comment by vjovanov** [comment]
Good point, it is still nicer than the string syntax. Maybe we should remove the string syntax altogether and just leave the symbols.

**Comment by cvogt** [comment]
The tuple constructor syntax allows record with non identifier keys. You have test cases for that. I won't add that to my implementation, but maybe it is a feature you want to support.

**Comment by vjovanov** [comment]
Well record field names must be statically known for records to work. I do not see the usecase for records whose keys should be modified at run-time. How would you access those fields in a meaningful (type-safe) way.

**Comment by cvogt** [comment]
I wasn't talking about runtime, I think I saw tests like Rec( 5 -> "foo" ). If you only allow Rec( ...= "foo") you couldn't create 5 -> anymore. Which is fine by me. Just pointing out that change to make sure you are aware of it.

**Comment by vjovanov** [comment]
We allow only string literals, and in case of 5 you would have to do Rec(`5`=5) which is OK I think.

**Comment by cvogt** [comment]
I don't think Rec(5=5) passes the scala parser. the lhs needs to be an identifier.
```
scala> class Foo extends Dynamic{ def applyDynamicNamed(method: String)(kvs: (String,Any)*) = kvs }
scala> new Foo().foo(5=5)
<console>:1: error: ')' expected but '=' found.
       new Foo().foo(5=5)
```

**Comment by vjovanov** [comment]
Ah markdown swallowed it: \`5\` does pass the parser.

**Comment by cvogt** [comment]
Ah interesting :).

**Comment by gzm0** [comment]
@vjovanov I propose we dismiss this. There is really no need for another syntax.

**Comment by vjovanov** [comment]
No need since we have the equals syntax. Close.

**Comment by cvogt** [comment]
+1
